# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-job:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.12
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # set up env
      - run:
          name: Setup Environment Variables
          command: |
            echo 'export GOOGLE_API_KEY="$GOOGLE_API_KEY"' >> $BASH_ENV
            echo 'export GOOGLE_CLIENT_ID="$GOOGLE_CLIENT_ID"' >> $BASH_ENV

      # run tests!
      - run: yarn test
      - run: yarn build
      - run: ls -la
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - package.json
            - dist
  deploy-job:
    docker:
      - image: circleci/node:8.12
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run: ls -la
      - run: yarn publish-dist

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job:
          filters:
            tags:
              only: /.*/

      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/
