# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
fragments:
  common-job-mixin: &common-job-mixin
    docker:
      - image: circleci/node:8.12
    working_directory: ~/repo
  common-job-steps-mixin:
    - checkout
    # Download and cache dependencies
    - restore_cache: &cache-restore-mixin
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
    - run: yarn install
    - save_cache: &cache-save-mixin
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

jobs:
  build-job:
    <<: *common-job-mixin
    steps:
      - checkout
      - restore_cache: *cache-restore-mixin
      - run: yarn install
      - save_cache: *cache-save-mixin

      # set up env
      - run:
          name: Setup Environment Variables
          command: |
            echo 'export GOOGLE_API_KEY="$GOOGLE_API_KEY"' >> $BASH_ENV
            echo 'export GOOGLE_CLIENT_ID="$GOOGLE_CLIENT_ID"' >> $BASH_ENV

      # run tests!
      - run: yarn test
      - run: yarn build
      - run: ls -la
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - package.json
            - dist
  deploy-job:
    <<: *common-job-mixin
    steps:
      - attach_workspace:
          at: ~/repo
      - run: ls -la
      - run: yarn publish-dist

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job:
          filters: &build-deploy-filters
            # ignore any commit on any branch by default
            branches:
              ignore: /.*/
            # only act on version tags
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/

      - deploy-job:
          requires:
            - build-job
          filters: *build-deploy-filters
